[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
# Note: These need to be set in Netlify dashboard
# VITE_SUPABASE_URL = "your_supabase_project_url"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"